version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=TVLqAAB6kxKKynQ6
      - POSTGRES_DB=autoscale
    ports:
      - "5432:5432"
    # volumes:
    #   - ./db/postgres:/var/lib/postgresql/data
    networks:
      - autoscale

  prometheus:
    image: bryanl/autoscale-prometheus
    ports:
      - "9090:9090"
    volumes:
      - /var/lib/autoscale/prometheus
    networks:
      - autoscale
  app:
    build: .
    image: do-autoscale
    env_file: dev.env
    ports:
      - "8888:8888"
    volumes_from:
      - prometheus
    networks:
      - autoscale

networks:
  autoscale:
    driver: bridge
